/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scope_msg_request.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "scope_msg_request.pb-c.h"
void   scope_msg_client_req__init
                     (ScopeMsgClientReq         *message)
{
  static ScopeMsgClientReq init_value = SCOPE_MSG_CLIENT_REQ__INIT;
  *message = init_value;
}
size_t scope_msg_client_req__get_packed_size
                     (const ScopeMsgClientReq *message)
{
  assert(message->base.descriptor == &scope_msg_client_req__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t scope_msg_client_req__pack
                     (const ScopeMsgClientReq *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &scope_msg_client_req__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t scope_msg_client_req__pack_to_buffer
                     (const ScopeMsgClientReq *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &scope_msg_client_req__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ScopeMsgClientReq *
       scope_msg_client_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ScopeMsgClientReq *)
     protobuf_c_message_unpack (&scope_msg_client_req__descriptor,
                                allocator, len, data);
}
void   scope_msg_client_req__free_unpacked
                     (ScopeMsgClientReq *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &scope_msg_client_req__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue scope_msg_client_req__scope_msg_id_req__enum_values_by_number[3] =
{
  { "SCOPE_MSGID_DUMMY_REQ", "SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_DUMMY_REQ", 0 },
  { "SCOPE_MSGID_REGISTER_REQ", "SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_REGISTER_REQ", 1 },
  { "SCOPE_MSGID_UNREGISTER_REQ", "SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_UNREGISTER_REQ", 2 },
};
static const ProtobufCIntRange scope_msg_client_req__scope_msg_id_req__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex scope_msg_client_req__scope_msg_id_req__enum_values_by_name[3] =
{
  { "SCOPE_MSGID_DUMMY_REQ", 0 },
  { "SCOPE_MSGID_REGISTER_REQ", 1 },
  { "SCOPE_MSGID_UNREGISTER_REQ", 2 },
};
const ProtobufCEnumDescriptor scope_msg_client_req__scope_msg_id_req__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scopeMsgClientReq.scopeMsgIdReq",
  "scopeMsgIdReq",
  "ScopeMsgClientReq__ScopeMsgIdReq",
  "",
  3,
  scope_msg_client_req__scope_msg_id_req__enum_values_by_number,
  3,
  scope_msg_client_req__scope_msg_id_req__enum_values_by_name,
  1,
  scope_msg_client_req__scope_msg_id_req__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue scope_msg_client_req__scope_register_flags_req__enum_values_by_number[2] =
{
  { "CLIENT_SW_VER", "SCOPE_MSG_CLIENT_REQ__SCOPE_REGISTER_FLAGS_REQ__CLIENT_SW_VER", 1 },
  { "CLIENT_NAME", "SCOPE_MSG_CLIENT_REQ__SCOPE_REGISTER_FLAGS_REQ__CLIENT_NAME", 2 },
};
static const ProtobufCIntRange scope_msg_client_req__scope_register_flags_req__value_ranges[] = {
{1, 0},{0, 2}
};
static const ProtobufCEnumValueIndex scope_msg_client_req__scope_register_flags_req__enum_values_by_name[2] =
{
  { "CLIENT_NAME", 1 },
  { "CLIENT_SW_VER", 0 },
};
const ProtobufCEnumDescriptor scope_msg_client_req__scope_register_flags_req__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "scopeMsgClientReq.scopeRegisterFlagsReq",
  "scopeRegisterFlagsReq",
  "ScopeMsgClientReq__ScopeRegisterFlagsReq",
  "",
  2,
  scope_msg_client_req__scope_register_flags_req__enum_values_by_number,
  2,
  scope_msg_client_req__scope_register_flags_req__enum_values_by_name,
  1,
  scope_msg_client_req__scope_register_flags_req__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor scope_msg_client_req__field_descriptors[4] =
{
  {
    "msg_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(ScopeMsgClientReq, msg_id),
    &scope_msg_client_req__scope_msg_id_req__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "device_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(ScopeMsgClientReq, device_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_flags",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(ScopeMsgClientReq, has_payload_flags),
    offsetof(ScopeMsgClientReq, payload_flags),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_data",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(ScopeMsgClientReq, has_payload_data),
    offsetof(ScopeMsgClientReq, payload_data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned scope_msg_client_req__field_indices_by_name[] = {
  1,   /* field[1] = device_id */
  0,   /* field[0] = msg_id */
  3,   /* field[3] = payload_data */
  2,   /* field[2] = payload_flags */
};
static const ProtobufCIntRange scope_msg_client_req__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor scope_msg_client_req__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "scopeMsgClientReq",
  "ScopeMsgClientReq",
  "ScopeMsgClientReq",
  "",
  sizeof(ScopeMsgClientReq),
  4,
  scope_msg_client_req__field_descriptors,
  scope_msg_client_req__field_indices_by_name,
  1,  scope_msg_client_req__number_ranges,
  (ProtobufCMessageInit) scope_msg_client_req__init,
  NULL,NULL,NULL    /* reserved[123] */
};
