/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: scope_msg_request.proto */

#ifndef PROTOBUF_C_scope_5fmsg_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_scope_5fmsg_5frequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1002001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _ScopeMsgClientReq ScopeMsgClientReq;


/* --- enums --- */

typedef enum _ScopeMsgClientReq__ScopeMsgIdReq {
  SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_DUMMY_REQ = 0,
  SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_REGISTER_REQ = 1,
  SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ__SCOPE_MSGID_UNREGISTER_REQ = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SCOPE_MSG_CLIENT_REQ__SCOPE_MSG_ID_REQ)
} ScopeMsgClientReq__ScopeMsgIdReq;
typedef enum _ScopeMsgClientReq__ScopeRegisterFlagsReq {
  SCOPE_MSG_CLIENT_REQ__SCOPE_REGISTER_FLAGS_REQ__CLIENT_SW_VER = 1,
  SCOPE_MSG_CLIENT_REQ__SCOPE_REGISTER_FLAGS_REQ__CLIENT_NAME = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SCOPE_MSG_CLIENT_REQ__SCOPE_REGISTER_FLAGS_REQ)
} ScopeMsgClientReq__ScopeRegisterFlagsReq;

/* --- messages --- */

struct  _ScopeMsgClientReq
{
  ProtobufCMessage base;
  ScopeMsgClientReq__ScopeMsgIdReq msg_id;
  int32_t device_id;
  protobuf_c_boolean has_payload_flags;
  int32_t payload_flags;
  protobuf_c_boolean has_payload_data;
  ProtobufCBinaryData payload_data;
};
#define SCOPE_MSG_CLIENT_REQ__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scope_msg_client_req__descriptor) \
    , 0, 0, 0,0, 0,{0,NULL} }


/* ScopeMsgClientReq methods */
void   scope_msg_client_req__init
                     (ScopeMsgClientReq         *message);
size_t scope_msg_client_req__get_packed_size
                     (const ScopeMsgClientReq   *message);
size_t scope_msg_client_req__pack
                     (const ScopeMsgClientReq   *message,
                      uint8_t             *out);
size_t scope_msg_client_req__pack_to_buffer
                     (const ScopeMsgClientReq   *message,
                      ProtobufCBuffer     *buffer);
ScopeMsgClientReq *
       scope_msg_client_req__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scope_msg_client_req__free_unpacked
                     (ScopeMsgClientReq *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*ScopeMsgClientReq_Closure)
                 (const ScopeMsgClientReq *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor scope_msg_client_req__descriptor;
extern const ProtobufCEnumDescriptor    scope_msg_client_req__scope_msg_id_req__descriptor;
extern const ProtobufCEnumDescriptor    scope_msg_client_req__scope_register_flags_req__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_scope_5fmsg_5frequest_2eproto__INCLUDED */
